/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.Ui.FacultyRole;

import info5100.university.example.Context.UniversityContext;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import javax.swing.JPanel;
import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
/**
 *
 * @author Srija
 */
public class FacultyWorkAreaJPanel extends javax.swing.JPanel {

    private UniversityContext ctx;
    private FacultyProfile me;
    private JPanel CardSequencePanel;
    /**
     * Creates new form FacultyWorkAreaJPanel
     */
    public FacultyWorkAreaJPanel(UniversityContext ctx, FacultyProfile me, JPanel cardPanel) {
        initComponents();
        this.ctx = ctx;
        this.me  = me;
        this.CardSequencePanel = cardPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageCourses = new javax.swing.JButton();
        btnmanageStudentsProfiles = new javax.swing.JButton();
        btnTuitionEnrollment = new javax.swing.JButton();
        btnPerformanceReports = new javax.swing.JButton();
        btnMyProfile1 = new javax.swing.JButton();

        btnManageCourses.setBackground(new java.awt.Color(102, 153, 255));
        btnManageCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCourses.setText(" Manage Courses");
        btnManageCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageCourses.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageCourses.setMinimumSize(new java.awt.Dimension(20, 23));
        btnManageCourses.setPreferredSize(new java.awt.Dimension(240, 30));
        btnManageCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCoursesIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnmanageStudentsProfiles.setBackground(new java.awt.Color(102, 153, 255));
        btnmanageStudentsProfiles.setForeground(new java.awt.Color(255, 255, 255));
        btnmanageStudentsProfiles.setText("Manage Students Profiles");
        btnmanageStudentsProfiles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnmanageStudentsProfiles.setMaximumSize(new java.awt.Dimension(200, 40));
        btnmanageStudentsProfiles.setMinimumSize(new java.awt.Dimension(20, 20));
        btnmanageStudentsProfiles.setPreferredSize(new java.awt.Dimension(240, 25));
        btnmanageStudentsProfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanageStudentsProfilesActionPerformed(evt);
            }
        });

        btnTuitionEnrollment.setBackground(new java.awt.Color(102, 153, 255));
        btnTuitionEnrollment.setForeground(new java.awt.Color(255, 255, 255));
        btnTuitionEnrollment.setText("Tuition/Enrollment");
        btnTuitionEnrollment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTuitionEnrollment.setMaximumSize(new java.awt.Dimension(145, 40));
        btnTuitionEnrollment.setMinimumSize(new java.awt.Dimension(20, 20));
        btnTuitionEnrollment.setPreferredSize(new java.awt.Dimension(240, 25));
        btnTuitionEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuitionEnrollmentIdentifyEventsActionPerformed(evt);
            }
        });

        btnPerformanceReports.setBackground(new java.awt.Color(102, 153, 255));
        btnPerformanceReports.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformanceReports.setText("Performance Reports");
        btnPerformanceReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerformanceReports.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPerformanceReports.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPerformanceReports.setPreferredSize(new java.awt.Dimension(240, 25));
        btnPerformanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceReportsActionPerformed(evt);
            }
        });

        btnMyProfile1.setBackground(new java.awt.Color(102, 153, 255));
        btnMyProfile1.setForeground(new java.awt.Color(255, 255, 255));
        btnMyProfile1.setText("My Profile");
        btnMyProfile1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMyProfile1.setMaximumSize(new java.awt.Dimension(145, 40));
        btnMyProfile1.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMyProfile1.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMyProfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfile1IdentifyEventsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMyProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTuitionEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnManageCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(btnmanageStudentsProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnPerformanceReports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(38, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(btnMyProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnTuitionEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnManageCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnmanageStudentsProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40)
                    .addComponent(btnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCoursesIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCoursesIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        /*CardSequencePanel.removeAll();

        ManagePersonsJPanel aos = new ManagePersonsJPanel(business, CardSequencePanel);

        CardSequencePanel.add("Manage Persons", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);*/
        
        try {
        info5100.university.example.Ui.FacultyRole.ManageCoursesJPanel p =
            new info5100.university.example.Ui.FacultyRole.ManageCoursesJPanel(ctx, me, CardSequencePanel);
        CardSequencePanel.add("ManageCourses", p);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    } catch (Throwable t) {
        javax.swing.JOptionPane.showMessageDialog(this, "ManageCourses not available yet.");
    }
    }//GEN-LAST:event_btnManageCoursesIdentifyResourceAssetsActionPerformed

    private void btnmanageStudentsProfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanageStudentsProfilesActionPerformed
        // TODO add your handling code here:
        ManageStudentsProfilesJPanel p =
    new ManageStudentsProfilesJPanel(ctx, me, CardSequencePanel);
CardSequencePanel.add("ManageStudentProfiles", p);
((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        /*javax.swing.JPanel panel = new javax.swing.JPanel();
    panel.add(new javax.swing.JLabel("Manage Student Profiles (placeholder)"));
    CardSequencePanel.add("ManageStudentProfiles", panel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "ManageStudentProfiles");*/

    }//GEN-LAST:event_btnmanageStudentsProfilesActionPerformed

    private void btnTuitionEnrollmentIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuitionEnrollmentIdentifyEventsActionPerformed
        // TODO add your handling code here:
        try {
        TuitionEnrollmentJPanel p = new TuitionEnrollmentJPanel(ctx, me, CardSequencePanel);
        CardSequencePanel.add("TuitionEnrollment", p);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    } catch (Throwable t) {
        javax.swing.JOptionPane.showMessageDialog(this, "Unable to open Tuition/Enrollment.");
    }
        /*CardSequencePanel.removeAll();
        //    IdentifyEventTypes iet= new IdentifyEventTypes(businessunit, CardSequencePanel);

        //    CardSequencePanel.add("IdentifyEventTypes", iet);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        //((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");*/
        /*javax.swing.JPanel panel = new javax.swing.JPanel();
    panel.add(new javax.swing.JLabel("Tuition / Enrollment (placeholder)"));
    CardSequencePanel.add("TuitionEnrollment", panel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "TuitionEnrollment");*/
        
    }//GEN-LAST:event_btnTuitionEnrollmentIdentifyEventsActionPerformed

    private void btnPerformanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceReportsActionPerformed
        // TODO add your handling code here:
        try {
        PerformanceReportsJPanel p = new PerformanceReportsJPanel(ctx, me, CardSequencePanel);
        CardSequencePanel.add("PerformanceReports", p);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    } catch (Throwable t) {
        javax.swing.JOptionPane.showMessageDialog(this, "Unable to open Performance Reports.");
    }
        /*javax.swing.JPanel panel = new javax.swing.JPanel();
    panel.add(new javax.swing.JLabel("Performance Reports (placeholder)"));
    CardSequencePanel.add("PerformanceReports", panel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "PerformanceReports");*/
    }//GEN-LAST:event_btnPerformanceReportsActionPerformed

    private void btnMyProfile1IdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfile1IdentifyEventsActionPerformed
        // TODO add your handling code here:
        /*javax.swing.JPanel panel = new javax.swing.JPanel();
    panel.add(new javax.swing.JLabel("My Profile (placeholder)"));
    CardSequencePanel.add("MyProfile", panel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "MyProfile");*/
        try {
        // Create the real ManageProfileJPanel and show it
        ManageProfileJPanel p = new ManageProfileJPanel(ctx, me, CardSequencePanel);
        CardSequencePanel.add("ManageProfile", p);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    } catch (Throwable t) {
        javax.swing.JOptionPane.showMessageDialog(this, "Unable to open Manage Profile.");
    }
    }//GEN-LAST:event_btnMyProfile1IdentifyEventsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCourses;
    private javax.swing.JButton btnMyProfile1;
    private javax.swing.JButton btnPerformanceReports;
    private javax.swing.JButton btnTuitionEnrollment;
    private javax.swing.JButton btnmanageStudentsProfiles;
    // End of variables declaration//GEN-END:variables
}
