/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.Ui.FacultyRole;

import info5100.university.example.Context.UniversityContext;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.CourseSchedule.SeatAssignment;
import info5100.university.example.Persona.Faculty.FacultyProfile;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileWriter;
import java.util.*;
/**
 *
 * @author Srija
 */
public class PerformanceReportsJPanel extends javax.swing.JPanel {

    private final UniversityContext ctx;
    private final FacultyProfile faculty;
    private final JPanel CardSequencePanel;
    /**
     * Creates new form PerformanceReportsJPanel
     */
    public PerformanceReportsJPanel(UniversityContext ctx, FacultyProfile faculty, JPanel cardPanel) {
        initComponents();
        this.ctx = ctx;
        this.faculty = faculty;
        this.CardSequencePanel = cardPanel;
        
        loadSemesters();
    loadCoursesForSelectedSemester();
    }
    
    private void loadSemesters() {
    cmbSemester.removeAllItems();
    if (ctx == null) return;
    java.util.List<String> terms = new java.util.ArrayList<String>(ctx.getAllSchedules().keySet());
    java.util.Collections.sort(terms);
    for (String t : terms) cmbSemester.addItem(t);
    if (cmbSemester.getItemCount() > 0) cmbSemester.setSelectedIndex(0);
}

private void loadCoursesForSelectedSemester() {
    cmbCourse.removeAllItems();
    String term = (String) cmbSemester.getSelectedItem();
    if (term == null || ctx == null) return;

    info5100.university.example.CourseSchedule.CourseSchedule cs = ctx.getSchedule(term);
    if (cs == null) return;

    java.util.List<info5100.university.example.CourseSchedule.CourseOffer> offers = cs.getCourseOffers();
    for (info5100.university.example.CourseSchedule.CourseOffer co : offers) {
        if (co != null && co.getFacultyProfile() == faculty) {
            cmbCourse.addItem(co.getCourseNumber());
        }
    }
    if (cmbCourse.getItemCount() == 0) cmbCourse.addItem("(none)");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSemester = new javax.swing.JLabel();
        cmbSemester = new javax.swing.JComboBox<>();
        lblCourse = new javax.swing.JLabel();
        cmbCourse = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnGenerateReport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();

        lblSemester.setText("Semester");

        cmbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSemesterActionPerformed(evt);
            }
        });

        lblCourse.setText("Course");

        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCourseActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("PERFORMANCE REPORTS");

        btnGenerateReport.setText("Generate Report");
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Metric", "Value"
            }
        ));
        jScrollPane1.setViewportView(tblReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitle)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSemester)
                                            .addComponent(lblCourse))
                                        .addGap(77, 77, 77)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(btnBack)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerateReport)
                .addGap(261, 261, 261))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(11, 11, 11)
                .addComponent(lblTitle)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSemester))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourse)
                    .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGenerateReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCourseActionPerformed

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        // TODO add your handling code here:
        String term = (String) cmbSemester.getSelectedItem();
    String cid  = (String) cmbCourse.getSelectedItem();
    if (term == null || cid == null || "(none)".equals(cid)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pick a semester and one of your courses.");
        return;
    }
    info5100.university.example.CourseSchedule.CourseSchedule cs = ctx.getSchedule(term);
    if (cs == null) { javax.swing.JOptionPane.showMessageDialog(this, "Semester not found."); return; }

    info5100.university.example.CourseSchedule.CourseOffer co = cs.getCourseOfferByNumber(cid);
    if (co == null || co.getFacultyProfile() != faculty) {
        javax.swing.JOptionPane.showMessageDialog(this, "Course not found or not assigned to you.");
        return;
    }

    int enrolled = co.getEnrolledCount();

    javax.swing.table.DefaultTableModel m =
        (javax.swing.table.DefaultTableModel) tblReport.getModel();
    m.setRowCount(0);
    m.addRow(new Object[]{"Semester", term});
    m.addRow(new Object[]{"Course", cid});
    m.addRow(new Object[]{"Enrollment Count", Integer.valueOf(enrolled)});
    m.addRow(new Object[]{"Average Grade", "N/A"});
    m.addRow(new Object[]{"Grade A", Integer.valueOf(0)});
    m.addRow(new Object[]{"Grade B", Integer.valueOf(0)});
    m.addRow(new Object[]{"Grade C", Integer.valueOf(0)});
    m.addRow(new Object[]{"Grade D", Integer.valueOf(0)});
    m.addRow(new Object[]{"Grade F", Integer.valueOf(0)});
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if (CardSequencePanel != null) {
        CardSequencePanel.remove(this);
        java.awt.CardLayout layout = (java.awt.CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSemesterActionPerformed
        // TODO add your handling code here:
        loadCoursesForSelectedSemester();
    }//GEN-LAST:event_cmbSemesterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JComboBox<String> cmbSemester;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables
}
