/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.Ui.FacultyRole;

import info5100.university.example.Context.UniversityContext;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import javax.swing.JPanel;

import info5100.university.example.Context.UniversityContext;
import info5100.university.example.CourseCatalog.Course;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.Persona.Faculty.FacultyProfile;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;

/**
 *
 * @author Srija
 */
public class TuitionEnrollmentJPanel extends javax.swing.JPanel {

    private final UniversityContext ctx;
    private final FacultyProfile faculty;
    private final JPanel CardSequencePanel;
    /**
     * Creates new form TuitionEnrollmentJPanel
     */
    public TuitionEnrollmentJPanel(UniversityContext ctx, FacultyProfile faculty, JPanel cardPanel) {
        initComponents();
        this.ctx = ctx;
    this.faculty = faculty;
    this.CardSequencePanel = cardPanel;
    
    refreshTuitionTable();
    }
    
    private void refreshTuitionTable(){
    javax.swing.table.DefaultTableModel m =
        (javax.swing.table.DefaultTableModel) tblTution.getModel();
    m.setRowCount(0);
    long grand = 0L;

    if (ctx == null || faculty == null) { txtTotal.setText("0"); return; }

    java.util.List<String> terms = new java.util.ArrayList<String>(ctx.getAllSchedules().keySet());
    java.util.Collections.sort(terms);

    for (String term : terms) {
        info5100.university.example.CourseSchedule.CourseSchedule cs = ctx.getSchedule(term);
        if (cs == null) continue;

        java.util.List<info5100.university.example.CourseSchedule.CourseOffer> offers = cs.getCourseOffers();
        for (info5100.university.example.CourseSchedule.CourseOffer co : offers) {
            if (co == null || co.getFacultyProfile() != faculty) continue;

            int enrolled = co.getEnrolledCount();
            int perStudent = 1000; // flat demo tuition (keep simple)
            int total = perStudent * enrolled;
            grand += total;

            String courseId = (co.getSubjectCourse() != null)
                    ? safe(co.getSubjectCourse().getCOurseNumber())
                    : safe(co.getCourseNumber());

            m.addRow(new Object[]{ term, courseId, Integer.valueOf(enrolled),
                                   Integer.valueOf(perStudent), Integer.valueOf(total) });
        }
    }
    txtTotal.setText(String.valueOf(grand));
}



private static String safe(String s){ return (s == null) ? "" : s; }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTution = new javax.swing.JTable();

        lblTotal.setText("Grand Total");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("TUTION ENROLLMENT");

        tblTution.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Semester", "Course_ID", "Enrolled", "Tution/Student", "Total Tution"
            }
        ));
        jScrollPane1.setViewportView(tblTution);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTitle))
                            .addComponent(btnBack)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(lblTotal)
                        .addGap(98, 98, 98)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(11, 11, 11)
                .addComponent(lblTitle)
                .addGap(127, 127, 127)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if (CardSequencePanel != null) {
        CardSequencePanel.remove(this);
        java.awt.CardLayout layout = (java.awt.CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
        }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblTution;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
