/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.Ui.AdminRole;

import java.awt.CardLayout;
import javax.swing.JPanel;

//private JPanel CardSequencePanel;

import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.PersonDirectory;
import info5100.university.example.Persona.UserAccountDirectory;
import info5100.university.example.Persona.UserAccount;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.Faculty.FacultyDirectory;
import info5100.university.example.CourseCatalog.CourseCatalog;
import info5100.university.example.CourseSchedule.CourseSchedule;

/**
 *
 * @author Srija
 */
public class AdminRoleWorkAreaJPanel extends javax.swing.JPanel {
    
    javax.swing.JPanel CardSequencePanel;

    /**
     * Creates new form AdminRoleWorkAreaJPanel
     */
    private PersonDirectory personDirectory;
    private UserAccountDirectory userAccountDirectory;
    private StudentDirectory studentDirectory;
    private FacultyDirectory facultyDirectory;
    private CourseCatalog courseCatalog;
    private CourseSchedule scheduleDirectory;
    private Person currentAdminPerson;
    private UserAccount currentAccount;
    
    public AdminRoleWorkAreaJPanel(PersonDirectory pDir,
                              UserAccountDirectory uaDir,
                              StudentDirectory sDir,
                              FacultyDirectory fDir,
                              CourseCatalog catalog,
                              CourseSchedule schedDir,
                              Person adminPerson,
                              javax.swing.JPanel cardSequencePanel,
                              UserAccount currentAccount) {
        initComponents();
        
        this.personDirectory = pDir;
        this.userAccountDirectory = uaDir;
        this.studentDirectory = sDir;
        this.facultyDirectory = fDir;
        this.courseCatalog = catalog;
        this.scheduleDirectory = schedDir;
        this.currentAdminPerson = adminPerson;
        
        this.CardSequencePanel = cardSequencePanel;
        this.currentAccount = currentAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdministeruserAccounts = new javax.swing.JButton();
        btnManageStudentsFacultyRegistrar = new javax.swing.JButton();
        btnRegisterPersons = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnMyProfile1 = new javax.swing.JButton();
        btnManageRegistrar = new javax.swing.JButton();
        btnManageFaculty = new javax.swing.JButton();

        btnAdministeruserAccounts.setBackground(new java.awt.Color(102, 153, 255));
        btnAdministeruserAccounts.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministeruserAccounts.setText("Administer User Accounts");
        btnAdministeruserAccounts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdministeruserAccounts.setMaximumSize(new java.awt.Dimension(200, 40));
        btnAdministeruserAccounts.setMinimumSize(new java.awt.Dimension(20, 23));
        btnAdministeruserAccounts.setPreferredSize(new java.awt.Dimension(240, 30));
        btnAdministeruserAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministeruserAccountsIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageStudentsFacultyRegistrar.setBackground(new java.awt.Color(102, 153, 255));
        btnManageStudentsFacultyRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnManageStudentsFacultyRegistrar.setText("Manage Students");
        btnManageStudentsFacultyRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageStudentsFacultyRegistrar.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageStudentsFacultyRegistrar.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageStudentsFacultyRegistrar.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageStudentsFacultyRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentsFacultyRegistrarActionPerformed(evt);
            }
        });

        btnRegisterPersons.setBackground(new java.awt.Color(102, 153, 255));
        btnRegisterPersons.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterPersons.setText("Register  Persons (HR)");
        btnRegisterPersons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegisterPersons.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRegisterPersons.setMinimumSize(new java.awt.Dimension(20, 20));
        btnRegisterPersons.setPreferredSize(new java.awt.Dimension(240, 25));
        btnRegisterPersons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPersonsActionPerformed(evt);
            }
        });

        btnReports.setBackground(new java.awt.Color(102, 153, 255));
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setText("Reports");
        btnReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReports.setMaximumSize(new java.awt.Dimension(200, 40));
        btnReports.setMinimumSize(new java.awt.Dimension(20, 20));
        btnReports.setPreferredSize(new java.awt.Dimension(240, 25));
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnMyProfile1.setBackground(new java.awt.Color(102, 153, 255));
        btnMyProfile1.setForeground(new java.awt.Color(255, 255, 255));
        btnMyProfile1.setText("My Profile");
        btnMyProfile1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMyProfile1.setMaximumSize(new java.awt.Dimension(145, 40));
        btnMyProfile1.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMyProfile1.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMyProfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfile1IdentifyEventsActionPerformed(evt);
            }
        });

        btnManageRegistrar.setBackground(new java.awt.Color(102, 153, 255));
        btnManageRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnManageRegistrar.setText("Manage Registrar");
        btnManageRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageRegistrar.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageRegistrar.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageRegistrar.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRegistrarActionPerformed(evt);
            }
        });

        btnManageFaculty.setBackground(new java.awt.Color(102, 153, 255));
        btnManageFaculty.setForeground(new java.awt.Color(255, 255, 255));
        btnManageFaculty.setText("Manage Faculty");
        btnManageFaculty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageFaculty.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageFaculty.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageFaculty.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFacultyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageStudentsFacultyRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdministeruserAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegisterPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMyProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdministeruserAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageStudentsFacultyRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMyProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterPersonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterPersonsActionPerformed
        // TODO add your handling code here:
        RegisterPersonsJPanel panel = new RegisterPersonsJPanel(personDirectory, studentDirectory, facultyDirectory, CardSequencePanel);
        CardSequencePanel.add("Register Persons", panel);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

        
    }//GEN-LAST:event_btnRegisterPersonsActionPerformed

    private void btnMyProfile1IdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfile1IdentifyEventsActionPerformed
        // TODO add your handling code here:
        ManageProfileJPanel panel = new ManageProfileJPanel(currentAccount, CardSequencePanel);
        CardSequencePanel.add("My Profile", panel);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnMyProfile1IdentifyEventsActionPerformed

    private void btnManageStudentsFacultyRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentsFacultyRegistrarActionPerformed
        ManageStudentsJPanel panel = new ManageStudentsJPanel(studentDirectory, CardSequencePanel);
        CardSequencePanel.add("Manage Students", panel);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageStudentsFacultyRegistrarActionPerformed

    private void btnAdministeruserAccountsIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministeruserAccountsIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        AdministerUserAccountsJPanel panel = new AdministerUserAccountsJPanel(personDirectory, userAccountDirectory, CardSequencePanel);
        CardSequencePanel.add("Administer User Accounts", panel);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

        
    }//GEN-LAST:event_btnAdministeruserAccountsIdentifyResourceAssetsActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        ReportsJPanel panel = new ReportsJPanel(userAccountDirectory, scheduleDirectory, studentDirectory, CardSequencePanel);
        CardSequencePanel.add("Reports", panel);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnManageRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRegistrarActionPerformed
        // TODO add your handling code here:
        ManageRegistrarJPanel panel = new ManageRegistrarJPanel(personDirectory, CardSequencePanel);
        CardSequencePanel.add("Manage Registrar", panel);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageRegistrarActionPerformed

    private void btnManageFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFacultyActionPerformed
        // TODO add your handling code here:
        ManageFacultyJPanel panel = new ManageFacultyJPanel(facultyDirectory, courseCatalog, scheduleDirectory, CardSequencePanel);
        CardSequencePanel.add("Manage Faculty", panel);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageFacultyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministeruserAccounts;
    private javax.swing.JButton btnManageFaculty;
    private javax.swing.JButton btnManageRegistrar;
    private javax.swing.JButton btnManageStudentsFacultyRegistrar;
    private javax.swing.JButton btnMyProfile1;
    private javax.swing.JButton btnRegisterPersons;
    private javax.swing.JButton btnReports;
    // End of variables declaration//GEN-END:variables
}
