/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.Ui.AdminRole;

import info5100.university.example.Persona.UserAccount;
import info5100.university.example.Persona.UserAccountDirectory;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.CourseSchedule.CourseOffer; // adjust if your class is different
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Srija
 */
public class ReportsJPanel extends javax.swing.JPanel {

    private UserAccountDirectory userAccountDirectory;
    private CourseSchedule courseSchedule;
    private StudentDirectory studentDirectory;
    private JPanel CardSequencePanel;
    /**
     * Creates new form ReportsJPanel
     */
    public ReportsJPanel(UserAccountDirectory uaDir,
                         CourseSchedule sched,
                         StudentDirectory sDir,
                         JPanel cardSequencePanel) {
        initComponents();
        this.userAccountDirectory = uaDir;
        this.courseSchedule = sched;
        this.studentDirectory = sDir;
        this.CardSequencePanel = cardSequencePanel;

        populateUsersByRole();
        populateCoursesBySemester();
        populateEnrollments();
        populateTuitionRevenue();
    }
    
    private void populateUsersByRole() {
        HashMap<String, Integer> counts = new HashMap<String, Integer>();
        ArrayList<UserAccount> list = userAccountDirectory.getUserAccountList();
        for (int i = 0; i < list.size(); i++) {
            String role = list.get(i).getRole();
            if (role == null) role = "Unknown";
            counts.put(role, counts.getOrDefault(role, 0) + 1);
        }
        DefaultTableModel dtm = (DefaultTableModel) tblUsersByRole.getModel();
        dtm.setRowCount(0);
        for (String r : counts.keySet()) {
            dtm.addRow(new Object[]{ r, counts.get(r) });
        }
    }

    private void populateCoursesBySemester() {
        
        DefaultTableModel dtm = (DefaultTableModel) tblCoursesBySemester.getModel();
        dtm.setRowCount(0);
        String term = courseSchedule.getSemester();                    // e.g., "Fall 2025"
        java.util.ArrayList<CourseOffer> offers = courseSchedule.getCourseOffers(); // list for this term
        int count = (offers != null) ? offers.size() : 0;

        dtm.addRow(new Object[]{ term, Integer.valueOf(count) });
    }

    private void populateEnrollments() {
        
        DefaultTableModel dtm = (DefaultTableModel) tblEnrollments.getModel();
        dtm.setRowCount(0);

        
        String term = courseSchedule.getSemester();
        ArrayList<CourseOffer> offers = courseSchedule.getCourseOffers();
        if (offers == null) return;

        for (int i = 0; i < offers.size(); i++) {
        CourseOffer co = offers.get(i);
        dtm.addRow(new Object[]{
            co.getCourseNumber(),   // Course ID
            co.getCourseName(),     // Course Name (fallbacks to number if name unavailable)
            term,                   // Semester
            co.getEnrolledCount()   // Enrolled Students
        });
    }
    }

    private void populateTuitionRevenue() {
        
        DefaultTableModel dtm = (DefaultTableModel) tblTuitionRevenue.getModel();
        dtm.setRowCount(0);
        
        double total = 0.0;
        ArrayList<StudentProfile> sp = studentDirectory.getStudentList();
        for (int i = 0; i < sp.size(); i++) {
            if (sp.get(i).getAccount() != null) {
                total += sp.get(i).getAccount().getTotalPaid(); // adjust if you have a different accessor
            }
        }
        dtm.addRow(new Object[]{ "All Terms", Double.valueOf(total) });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsersByRole = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCoursesBySemester = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTuitionRevenue = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEnrollments = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        tblUsersByRole.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Role", "Active Users"
            }
        ));
        jScrollPane1.setViewportView(tblUsersByRole);

        tblCoursesBySemester.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Semester", "Courses Offered"
            }
        ));
        jScrollPane2.setViewportView(tblCoursesBySemester);

        tblTuitionRevenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Semester", "Total Tuition"
            }
        ));
        jScrollPane4.setViewportView(tblTuitionRevenue);

        tblEnrollments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Semester", "Enrolled Students"
            }
        ));
        jScrollPane3.setViewportView(tblEnrollments);

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnBack)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addGap(9, 9, 9))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblCoursesBySemester;
    private javax.swing.JTable tblEnrollments;
    private javax.swing.JTable tblTuitionRevenue;
    private javax.swing.JTable tblUsersByRole;
    // End of variables declaration//GEN-END:variables
}
