/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package info5100.university.example.Ui;

import java.awt.CardLayout;
import javax.swing.JPanel;


import info5100.university.example.Context.UniversityContext;

import info5100.university.example.CourseCatalog.CourseCatalog;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.Persona.PersonDirectory;
import info5100.university.example.Persona.UserAccountDirectory;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.Faculty.FacultyDirectory;
import info5100.university.example.Ui.StudentRole.StudentWorkAreaJPanel;
/**
 *
 * @author Srija
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private JPanel CardSequencePanel; // alias to workAreajPanel (right-side card container)
// at top of MainJFrame
private javax.swing.JPanel contentPanel;   // our alias to the card container
    private UniversityContext ctx;
    private PersonDirectory personDirectory;
    private UserAccountDirectory userAccountDirectory;
    private StudentDirectory studentDirectory;
    private FacultyDirectory facultyDirectory;
    private CourseCatalog courseCatalog;
    private CourseSchedule courseSchedule;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.CardSequencePanel = workAreajPanel;
        
        this.ctx = info5100.university.example.bootstrap.ConfigureAUniversity.init();
        
        info5100.university.example.Context.UniversityContext ctx =
            info5100.university.example.bootstrap.ConfigureAUniversity.init();

        info5100.university.example.Department.Department dept = ctx.getDepartment();
        
        //Department dept = new Department("Information Systems");
        this.personDirectory   = dept.getPersonDirectory();
    this.studentDirectory  = dept.getStudentDirectory();
    this.facultyDirectory  = dept.getFacultyDirectory(); // if you already have one, use it
    this.courseCatalog     = dept.getCourseCatalog();
    this.courseSchedule    = ctx.getSchedule("Fall 2025");

    // If you want to allow login with seeded accounts from ConfigureAUniversity:
    this.userAccountDirectory = new info5100.university.example.Persona.UserAccountDirectory();
    // copy AuthManager accounts into this directory (simple bridge)
    for (info5100.university.example.Persona.UserAccount ua : ctx.getAuth().getAllAccounts()) {
        if (userAccountDirectory.findByUsername(ua.getUserLoginName()) == null) {
            userAccountDirectory.createUserAccount(
                ua.getUserLoginName(),
                ua.getPassword(),
                ua.getPerson(),
                ua.getRole()
            );
        }
    }

        // Optional: show a blank/welcome panel on the right
        CardSequencePanel.add("WELCOME", new javax.swing.JPanel());
        ((CardLayout) CardSequencePanel.getLayout()).first(CardSequencePanel);
    }
  public void showCard(String id) {
    if (contentPanel.getLayout() instanceof CardLayout) {
        ((CardLayout) contentPanel.getLayout()).show(contentPanel, id);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        actionsidejPanel = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        workAreajPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        actionsidejPanel.setBackground(new java.awt.Color(153, 204, 255));

        lblUsername.setText("Username");

        lblPassword.setText("Password");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionsidejPanelLayout = new javax.swing.GroupLayout(actionsidejPanel);
        actionsidejPanel.setLayout(actionsidejPanelLayout);
        actionsidejPanelLayout.setHorizontalGroup(
            actionsidejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsidejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionsidejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername)
                    .addComponent(lblPassword)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        actionsidejPanelLayout.setVerticalGroup(
            actionsidejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsidejPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(actionsidejPanel);

        workAreajPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workAreajPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String un = txtUsername.getText().trim();
    String pw = txtPassword.getText().trim();

    if (un.isEmpty() || pw.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Enter username and password.");
        return;
    }

    // 1) Authenticate against your model
    info5100.university.example.Persona.UserAccount ua =
            userAccountDirectory.IsValidUser(un, pw);
    if (ua == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid credentials.");
        return;
    }

    // 2) Decide by role (Admin | Faculty | Student | Registrar)
    String role = ua.getRole();
    info5100.university.example.Persona.Person person = ua.getPerson(); // may be null if not linked

    if ("Admin".equalsIgnoreCase(role)) {
    info5100.university.example.Ui.AdminRole.AdminRoleWorkAreaJPanel panel =
        new info5100.university.example.Ui.AdminRole.AdminRoleWorkAreaJPanel(
            personDirectory,
            userAccountDirectory,
            studentDirectory,
            facultyDirectory,
            courseCatalog,
            courseSchedule,
            person,
            workAreajPanel,
            ua // pass current account so MyProfile can populate
        );
    workAreajPanel.removeAll();
    workAreajPanel.add("Admin", panel);
    ((java.awt.CardLayout) workAreajPanel.getLayout()).next(workAreajPanel);
    return;
    }
    
    if ("Registrar".equalsIgnoreCase(role)) {
    info5100.university.example.Ui.RegistrarRole.RegistrarWorkAreaJPanel panel =
        new info5100.university.example.Ui.RegistrarRole.RegistrarWorkAreaJPanel(
            ctx,              // <— pass the whole context
            workAreajPanel,   // the card panel
            ua                // current account (for ManageProfile)
        );
    workAreajPanel.removeAll();
    workAreajPanel.add("Registrar", panel);
    ((java.awt.CardLayout) workAreajPanel.getLayout()).next(workAreajPanel);
    return;
}


    /*if ("Registrar".equalsIgnoreCase(role)) {
        // Using your existing Registrar manager panel as the registrar's home for now
        info5100.university.example.Ui.AdminRole.ManageRegistrarJPanel panel =
            new info5100.university.example.Ui.AdminRole.ManageRegistrarJPanel(
                personDirectory,
                workAreajPanel
            );
        workAreajPanel.removeAll();
        workAreajPanel.add("Registrar", panel);
        ((java.awt.CardLayout) workAreajPanel.getLayout()).next(workAreajPanel);
        return;
    }*/

    if ("Faculty".equalsIgnoreCase(role)) {
        // Minimal placeholder so app runs without errors until you share FacultyWorkAreaJPanel
        javax.swing.JPanel placeholder = new javax.swing.JPanel();
        placeholder.add(new javax.swing.JLabel("Faculty Work Area - to be wired"));
        workAreajPanel.removeAll();
        workAreajPanel.add("Faculty", placeholder);
        ((java.awt.CardLayout) workAreajPanel.getLayout()).next(workAreajPanel);
        return;
    }

    if ("Student".equalsIgnoreCase(role)) {
    // Build the real Student hub
    StudentWorkAreaJPanel panel = new StudentWorkAreaJPanel(
        ctx,              // full model context (has dept, dirs, schedules)
        workAreajPanel,   // the right-side CardLayout container
        ua                // the logged-in user (for profile lookups)
    );
    workAreajPanel.removeAll();
    workAreajPanel.add("StudentHome", panel);
    ((java.awt.CardLayout) workAreajPanel.getLayout()).next(workAreajPanel);

    // (nice to have) clear login fields
    txtUsername.setText("");
    txtPassword.setText("");

    return;
}

    javax.swing.JOptionPane.showMessageDialog(this, "Unknown role: " + role);
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionsidejPanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPanel workAreajPanel;
    // End of variables declaration//GEN-END:variables
}
