/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.Ui.RegistrarRole;

import info5100.university.example.CourseCatalog.CourseCatalog;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Faculty.FacultyDirectory;
import info5100.university.example.Persona.PersonDirectory;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.UserAccount;
import javax.swing.JPanel;
import info5100.university.example.Context.UniversityContext;

/**
 *
 * @author Srija
 */
public class RegistrarWorkAreaJPanel extends javax.swing.JPanel {
    
private final Department department;
private final PersonDirectory personDirectory;
private final StudentDirectory studentDirectory;
private final FacultyDirectory facultyDirectory;
private final CourseCatalog courseCatalog;
private CourseSchedule activeSchedule;
private final UserAccount currentAccount;
private final JPanel CardSequencePanel;
private UniversityContext ctx;

    public RegistrarWorkAreaJPanel(UniversityContext ctx,
                                   JPanel cardPanel,
                                   UserAccount account) {
        initComponents();
        this.ctx = ctx;
        this.CardSequencePanel = cardPanel;
        this.currentAccount = account;

        // Pull everything from the context/department
        this.department       = ctx.getDepartment();
        this.personDirectory  = department.getPersonDirectory();
        this.studentDirectory = department.getStudentDirectory();
        // IMPORTANT: reuse the department’s faculty directory (don’t new it)
        this.facultyDirectory = department.getFacultyDirectory();
        this.courseCatalog    = department.getCourseCatalog();

        // Choose an active schedule (try “Fall 2025”, otherwise first available)
        this.activeSchedule = ctx.getSchedule("Fall 2025");
        if (this.activeSchedule == null) {
            this.activeSchedule = firstScheduleOrNull(ctx);
        }

        // If you need any initial population now, call your own methods here.
        // e.g., refresh buttons/tables/combos if you do that in constructor.
    }

    // helper to pick a schedule if "Fall 2025" wasn't added in ConfigureAUniversity
    private CourseSchedule firstScheduleOrNull(UniversityContext ctx) {
        for (CourseSchedule cs : ctx.getAllSchedules().values()) return cs;
        return null;
    }

    /**
     * Creates new form RegistrarWorkAreaJPanel
     */
    public RegistrarWorkAreaJPanel(Department dept,
                               PersonDirectory pDir,
                               StudentDirectory sDir,
                               FacultyDirectory fDir,
                               CourseCatalog catalog,
                               CourseSchedule active,
                               UserAccount account,
                               JPanel cardPanel) {
        initComponents();
        this.department = dept;
    this.personDirectory = pDir;
    this.studentDirectory = sDir;
    this.facultyDirectory = fDir;
    this.courseCatalog = catalog;
    this.activeSchedule = active;
    this.currentAccount = account;
    this.CardSequencePanel = cardPanel;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTuitionFinancial = new javax.swing.JButton();
        btnStudentRegistration = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnManageCourseOffering = new javax.swing.JButton();
        btnManageProfile = new javax.swing.JButton();

        btnTuitionFinancial.setBackground(new java.awt.Color(102, 153, 255));
        btnTuitionFinancial.setForeground(new java.awt.Color(255, 255, 255));
        btnTuitionFinancial.setText("Tuition & Financial Reconciliation");
        btnTuitionFinancial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTuitionFinancial.setMaximumSize(new java.awt.Dimension(200, 40));
        btnTuitionFinancial.setMinimumSize(new java.awt.Dimension(20, 20));
        btnTuitionFinancial.setPreferredSize(new java.awt.Dimension(240, 25));
        btnTuitionFinancial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuitionFinancialActionPerformed(evt);
            }
        });

        btnStudentRegistration.setBackground(new java.awt.Color(102, 153, 255));
        btnStudentRegistration.setForeground(new java.awt.Color(255, 255, 255));
        btnStudentRegistration.setText("Student Registration");
        btnStudentRegistration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStudentRegistration.setMaximumSize(new java.awt.Dimension(200, 40));
        btnStudentRegistration.setMinimumSize(new java.awt.Dimension(20, 20));
        btnStudentRegistration.setPreferredSize(new java.awt.Dimension(240, 25));
        btnStudentRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentRegistrationActionPerformed(evt);
            }
        });

        btnReports.setBackground(new java.awt.Color(102, 153, 255));
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setText("Reports");
        btnReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReports.setMaximumSize(new java.awt.Dimension(200, 40));
        btnReports.setMinimumSize(new java.awt.Dimension(20, 20));
        btnReports.setPreferredSize(new java.awt.Dimension(240, 25));
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnManageCourseOffering.setBackground(new java.awt.Color(102, 153, 255));
        btnManageCourseOffering.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCourseOffering.setText("Manage Course Offering");
        btnManageCourseOffering.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageCourseOffering.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageCourseOffering.setMinimumSize(new java.awt.Dimension(20, 23));
        btnManageCourseOffering.setPreferredSize(new java.awt.Dimension(240, 30));
        btnManageCourseOffering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCourseOfferingIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnManageProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnManageProfile.setText("Manage Profile");
        btnManageProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageProfile.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnReports, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnManageCourseOffering, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                        .addComponent(btnManageProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGap(75, 75, 75)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnStudentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTuitionFinancial, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnManageCourseOffering, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnStudentRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(56, 56, 56)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnManageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTuitionFinancial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(43, 43, 43)
                    .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTuitionFinancialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuitionFinancialActionPerformed
        // TODO add your handling code here:
        TuitionFinancesReconciliationJPanel p = new TuitionFinancesReconciliationJPanel(
        ctx,CardSequencePanel);
    CardSequencePanel.add("TuitionRecon", p);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnTuitionFinancialActionPerformed

    private void btnStudentRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentRegistrationActionPerformed
        // TODO add your handling code here:
        StudentRegistrationJPanel p = new StudentRegistrationJPanel(
        ctx, CardSequencePanel);
    CardSequencePanel.add("StudentRegistration", p);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

        
    }//GEN-LAST:event_btnStudentRegistrationActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        ReportsJPanel p = new ReportsJPanel(ctx, CardSequencePanel);
    CardSequencePanel.add("Reports", p);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnManageCourseOfferingIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCourseOfferingIdentifyResourceAssetsActionPerformed

        /*ManageCourseOfferingJPanel p = new ManageCourseOfferingJPanel(
        ctx, facultyDirectory, CardSequencePanel);*/
        ManageCourseOfferingJPanel p = new ManageCourseOfferingJPanel(
        ctx, department.getFacultyDirectory(), CardSequencePanel);
    
    CardSequencePanel.add("ManageCourseOffering", p);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageCourseOfferingIdentifyResourceAssetsActionPerformed

    private void btnManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileActionPerformed
        // TODO add your handling code here:
        ManageProfileJPanel p = new ManageProfileJPanel(
        currentAccount, CardSequencePanel);
    CardSequencePanel.add("MyProfile", p);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnManageProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCourseOffering;
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnStudentRegistration;
    private javax.swing.JButton btnTuitionFinancial;
    // End of variables declaration//GEN-END:variables
}
