/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.Ui.RegistrarRole;

import info5100.university.example.Context.UniversityContext;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.CourseSchedule.SeatAssignment;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Srija
 */
public class ReportsJPanel extends javax.swing.JPanel {
    private final JPanel CardSequencePanel;
    private final UniversityContext ctx;

    /**
     * Creates new form ReportsJPanel
     */
    public ReportsJPanel(UniversityContext ctx, JPanel cardSequencePanel) {
        initComponents();
        this.ctx = ctx;
        this.CardSequencePanel = cardSequencePanel;

        runReports();
    }
    
    private void runReports() {
        populateEnrollmentByCourse();
        populateGpaDistribution();
    }
    
    private void populateEnrollmentByCourse() {
        DefaultTableModel dtm = (DefaultTableModel) tblEnrollmentByCourse.getModel();
        dtm.setRowCount(0);

        String deptName = ctx.getDepartment().getName();
        for (Map.Entry<String, CourseSchedule> e : ctx.getAllSchedules().entrySet()) {
            CourseSchedule cs = e.getValue();
            if (cs == null) continue;

            for (CourseOffer co : cs.getCourseOffers()) {
                String cid = co.getCourseNumber();
                String cname = co.getCourseName();
                int enrolled = co.getEnrolledCount();

                dtm.addRow(new Object[]{ deptName, cid, cname, enrolled });
            }
        }
    }

    // ---------------- GPA distribution ----------------

    private void populateGpaDistribution() {
        DefaultTableModel dtm = (DefaultTableModel) tblGpaDistribution.getModel();
        dtm.setRowCount(0);

        StudentDirectory sd = ctx.getDepartment().getStudentDirectory();

        int countHigh = 0;   // >= 3.7
        int countMid  = 0;   // 3.0 - 3.69...
        int countLow  = 0;   // < 3.0

        for (StudentProfile sp : sd.getStudentList()) {
            // GPA = total grade points / total credits
            double points = 0.0;
            int credits = 0;

            ArrayList<SeatAssignment> all = sp.getCourseList();
            for (SeatAssignment sa : all) {
                // GetCourseStudentScore() = credits * grade
                points += sa.GetCourseStudentScore();
                credits += sa.getCreditHours();
            }
            if (credits <= 0) continue; // no GPA yet

            double gpa = points / credits;

            if (gpa >= 3.7) countHigh++;
            else if (gpa >= 3.0) countMid++;
            else countLow++;
        }

        // Your table columns: Program, GPA>=3.7, 3.7>GPA>=3.0, GPA<3.0
        // If you have multiple programs, expand here; for now, single MSIS (dept degree).
        dtm.addRow(new Object[]{
                "MSIS", countHigh, countMid, countLow
        });
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneEnrollByCourse = new javax.swing.JScrollPane();
        tblEnrollmentByCourse = new javax.swing.JTable();
        jScrollPaneGpaDist = new javax.swing.JScrollPane();
        tblGpaDistribution = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();

        tblEnrollmentByCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Department", "Course ID", "Course Name", "Enrolled"
            }
        ));
        jScrollPaneEnrollByCourse.setViewportView(tblEnrollmentByCourse);

        tblGpaDistribution.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Program", "GPA≥3.7", "3.7>GPA≥3.0", "GPA<3.0"
            }
        ));
        jScrollPaneGpaDist.setViewportView(tblGpaDistribution);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRun.setText("Run");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRun)
                .addGap(81, 81, 81))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPaneEnrollByCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPaneGpaDist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(329, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRun)
                    .addComponent(btnBack))
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jScrollPaneEnrollByCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPaneGpaDist, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        // TODO add your handling code here:
        runReports();
    }//GEN-LAST:event_btnRunActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRun;
    private javax.swing.JScrollPane jScrollPaneEnrollByCourse;
    private javax.swing.JScrollPane jScrollPaneGpaDist;
    private javax.swing.JTable tblEnrollmentByCourse;
    private javax.swing.JTable tblGpaDistribution;
    // End of variables declaration//GEN-END:variables
}
